#ifndef __T_INTPID_H__
#define __T_INTPID_H__

typedef char I8;
typedef unsigned char U8;
typedef short I16;
typedef unsigned short U16;


typedef int I32;
typedef unsigned int U32;

enum IntpID {
    MPEG_HPEL = 0,
    MPEG_QPEL,
    H264_QPEL,
    H264_EPEL,
    RV8_TPEL,
    RV9_EPEL,
    RV9_QPEL,
    RV9_CPEL,
    WMV2_QPEL,
    VC1_QPEL,
    AVS_QPEL,
    VP6_QPEL,
    VP8_QPEL,
    VP8_EPEL,
    VP8_BIL,
    VP8_FPEL, /*full-pixel for chroma*/ 
};

enum PosID {
    H0V0 = 0,
    H1V0,
    H2V0,
    H3V0,
    H0V1,
    H1V1,
    H2V1,
    H3V1,
    H0V2,
    H1V2,
    H2V2,
    H3V2,
    H0V3,
    H1V3,
    H2V3,
    H3V3,
};

enum TapTYP {
    TAP2 = 0,
    TAP4,
    TAP6,
    TAP8,
};

enum SPelSFT {
    HPEL = 1,
    QPEL,
    EPEL,
};

enum BlkTYP {
    BLK16X16 = 0,
    BLK16X8,
    BLK8X16,
    BLK8X8,
};
enum SBlkTYP {
    NOSUB = 0,
    SBLK8X4,
    SBLK4X8,
    SBLK4X4,
};

#define NO_RESET  0
#define DO_RESET  1

#define IS_FRAME  0
#define IS_FIELD  1

#define IS_SKIRT  0
#define IS_MIRROR 1

#define NOT_RGR   0
#define IS_RGR    1
#define NOT_ITS   0
#define IS_ITS    1    

#define IS_BIAVG  0
#define IS_WT1    1
#define IS_WT2    2
#define IS_FIXWT  3

#define IS_ILUT0  0
#define IS_ILUT1  2
#define IS_EC     1

#define IS_TCS     1
#define NOT_TCS    0
#define IS_SCS     1
#define NOT_SCS    0
#define IS_HLDGL   1
#define NOT_HLDGL  0
#define IS_AVSDGL  1
#define NOT_AVSDGL 0

#define INTP_HDIR  0
#define INTP_VDIR  1

typedef struct IntpFMT_t{
    U8 tap;
    U8 intp_pkg[2];
    U8 hldgl;
    U8 avsdgl;
    U8 intp[2];
    U8 intp_dir[2];
    I8 intp_coef[2][8];
    I8 intp_rnd[2];
    U8 intp_sft[2];
    U8 intp_sintp[2];
    U8 intp_srnd[2];
    U8 intp_sbias[2];
}IntpFMT_t;

typedef struct CompVector_t{
    /*MB information*/
    U8 mbx, mby;
    U8 mbtype;
    U8 rst;
    U8 automv;
    U8 mbpar, subpar[4];
    U8 field[4];
    U8 list[2][4], refn[2][4];
    I16 mvx[2][4][4][2], mvy[2][4][4][2];
    /*Ext. information*/
    U8 intpid;
    U8 cintpid;
    U8 rgr;
    U8 its;
    I8 its_scale;
    I16 its_rnd;
    U8 its_sft;
    U8 wt_mode;
    U8 wt_denom;
    I8 wt_lcoef, wt_rcoef;
    I8 wt_rnd;
    U8 wt_sft;
    /*Golden*/
    U8 std_y[256];
    U8 std_u[64];
    U8 std_v[64];
}CompVector_t;

typedef struct WTpara_t{
    I8 wcoef_y;
    I8 wofst_y;
    I8 wcoef_u;
    I8 wofst_u;
    I8 wcoef_v;
    I8 wofst_v;
}WTpara_t;

static char AryFMT[] = {IS_SKIRT, IS_MIRROR, IS_SKIRT, IS_SKIRT,
			IS_SKIRT, IS_SKIRT, IS_SKIRT, IS_SKIRT, IS_SKIRT, 
			IS_SKIRT, IS_SKIRT, IS_SKIRT, IS_SKIRT, 
			IS_SKIRT, IS_SKIRT, IS_SKIRT, IS_SKIRT};

__place_k0_data__
static char SubPel[] = {HPEL, QPEL, QPEL, EPEL, 
			QPEL, QPEL, QPEL, QPEL, QPEL,
			QPEL, QPEL, QPEL, QPEL, 
			EPEL, HPEL, QPEL, QPEL};

__place_k0_data__
static IntpFMT_t IntpFMT[][16] = {
    {
	/************* MPEG_HPEL ***************/
	{/*H0V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H2V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H0V1*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V1*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
	    {/*intp_rnd*/0, 2}, 
	    {/*intp_sft*/0, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H2V1*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
	    {/*intp_rnd*/0, 2}, 
	    {/*intp_sft*/0, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V1*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
	    {/*intp_rnd*/0, 2}, 
	    {/*intp_sft*/0, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H0V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
	    {/*intp_rnd*/0, 2}, 
	    {/*intp_sft*/0, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H2V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
	    {/*intp_rnd*/0, 2}, 
	    {/*intp_sft*/0, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
	    {/*intp_rnd*/0, 2}, 
	    {/*intp_sft*/0, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H0V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
	    {/*intp_rnd*/0, 2}, 
	    {/*intp_sft*/0, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H2V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
	    {/*intp_rnd*/0, 2}, 
	    {/*intp_sft*/0, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
	    {/*intp_rnd*/0, 2}, 
	    {/*intp_sft*/0, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
    },
  
    {
	/************* MPEG_QPEL ***************/
	{/*H0V0*/
	    TAP8, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1},{0},},
	    {/*intp_rnd*/15, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/1, 0},
	    {/*intp_srnd*/1, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V0*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1},{0},},
	    {/*intp_rnd*/15, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V0*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1},{0},},
	    {/*intp_rnd*/15, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/1, 0},
	    {/*intp_srnd*/1, 0},
	    {/*intp_sbias*/1, 0},
	},
	{/*H0V1*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1},{0},},
	    {/*intp_rnd*/15, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/1, 0},
	    {/*intp_srnd*/1, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V1*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
	    {/*intp_rnd*/15, 15}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/1, 1},
	    {/*intp_srnd*/1, 1},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V1*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
	    {/*intp_rnd*/15, 15}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V1*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
	    {/*intp_rnd*/15, 15}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/1, 1},
	    {/*intp_srnd*/1, 1},
	    {/*intp_sbias*/1, 0},
	},
	{/*H0V2*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1},{0},},
	    {/*intp_rnd*/15, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V2*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
	    {/*intp_rnd*/15, 15}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/1, 0},
	    {/*intp_srnd*/1, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V2*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
	    {/*intp_rnd*/15, 15}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V2*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
	    {/*intp_rnd*/15, 15}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/1, 0},
	    {/*intp_srnd*/1, 0},
	    {/*intp_sbias*/1, 0},
	},
	{/*H0V3*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1},{0},},
	    {/*intp_rnd*/15, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/1, 0},
	    {/*intp_srnd*/1, 0},
	    {/*intp_sbias*/1, 0},
	},
	{/*H1V3*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
	    {/*intp_rnd*/15, 15}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/1, 1},
	    {/*intp_srnd*/1, 1},
	    {/*intp_sbias*/0, 1},
	},
	{/*H2V3*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
	    {/*intp_rnd*/15, 15}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/0, 1},
	},
	{/*H3V3*/
	    TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
	    {/*intp_rnd*/15, 15}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/1, 1},
	    {/*intp_srnd*/1, 1},
	    {/*intp_sbias*/1, 1},
	},
    },

    {
	/************* H264_QPEL ***************/
	{/*H0V0*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/1, 0},
	    {/*intp_srnd*/1, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V0*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V0*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/1, 0},
	    {/*intp_srnd*/1, 0},
	    {/*intp_sbias*/1, 0},
	},
	{/*H0V1*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/1, 0},
	    {/*intp_srnd*/1, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V1*/
	    TAP6, {NOT_TCS, IS_SCS}, IS_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/16, 16}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V1*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 10},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V1*/
	    TAP6, {NOT_TCS, IS_SCS}, IS_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/16, 16}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/1, 0},
	},
	{/*H0V2*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V2*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 10},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V2*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 10},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V2*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 10},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/0, 1},
	},
	{/*H0V3*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/1, 0},
	    {/*intp_srnd*/1, 0},
	    {/*intp_sbias*/1, 0},
	},
	{/*H1V3*/
	    TAP6, {NOT_TCS, IS_SCS}, IS_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/16, 16}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/0, 1},
	},
	{/*H2V3*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 10},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/0, 1},
	},
	{/*H3V3*/
	    TAP6, {NOT_TCS, IS_SCS}, IS_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/16, 16}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/1, 1},
	},
    },

    {
	/************* H264_EPEL ***************/
	{/*H0V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/0},
	{/*H2V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{0},{0},},
	    {/*intp_rnd*/4, 0}, 
	    {/*intp_sft*/3, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V0*/0},
	{/*H0V1*/0},
	{/*H1V1*/0},
	{/*H2V1*/0},
	{/*H3V1*/0},
	{/*H0V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{0},{0},},
	    {/*intp_rnd*/4, 0}, 
	    {/*intp_sft*/3, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V2*/0},
	{/*H2V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{0},{0},},
	    {/*intp_rnd*/0, 32}, 
	    {/*intp_sft*/0, 6},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V2*/0},
	{/*H0V3*/0},
	{/*H1V3*/0},
	{/*H2V3*/0},
	{/*H3V3*/0},
    },

    {
	/************* RV8_TPEL ***************/
	{/*H0V0*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-1, 12, 6, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/8, 0}, 
	    {/*intp_sft*/4, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V0*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-1, 6, 12, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/8, 0}, 
	    {/*intp_sft*/4, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V0*/0},
	{/*H0V1*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-1, 12, 6, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/8, 0}, 
	    {/*intp_sft*/4, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V1*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 12, 6, -1, 0, 0, 0, 0}, {-1, 12, 6, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/8, 0}, //{0,128}
	    {/*intp_sft*/0, 8},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V1*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 6, 12, -1, 0, 0, 0, 0}, {-1, 12, 6, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/8, 0}, //{0,128}
	    {/*intp_sft*/0, 8},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V1*/0},
	{/*H0V2*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-1, 6, 12, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/8, 0}, 
	    {/*intp_sft*/4, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V2*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 12, 6, -1, 0, 0, 0, 0}, {-1, 6, 12, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/8, 0}, //{0,128}
	    {/*intp_sft*/0, 8},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V2*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 6, 12, -1, 0, 0, 0, 0}, {-1, 6, 12, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/8, 0}, //{0,128}
	    {/*intp_sft*/0, 8},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V2*/0},
	{/*H0V3*/0},
	{/*H1V3*/0},
	{/*H2V3*/0},
	{/*H3V3*/0},
    },

    {
	/************* RV9_EPEL ***************/
	{/*H0V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{2, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/2, 0}, 
	    {/*intp_sft*/2, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H2V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/2, 0}, 
	    {/*intp_sft*/2, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H0V1*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/2, 0}, 
	    {/*intp_sft*/2, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V1*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{6, 2, 0, 0, 0, 0, 0, 0},{3, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 16}, 
	    {/*intp_sft*/0, 5},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H2V1*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{4, 4, 0, 0, 0, 0, 0, 0},{3, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 16}, 
	    {/*intp_sft*/0, 5},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V1*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{2, 6, 0, 0, 0, 0, 0, 0},{3, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 16}, 
	    {/*intp_sft*/0, 5},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H0V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{6, 2, 0, 0, 0, 0, 0, 0},{1, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 8}, 
	    {/*intp_sft*/0, 4},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H2V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{4, 4, 0, 0, 0, 0, 0, 0},{1, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 8}, 
	    {/*intp_sft*/0, 4},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{2, 6, 0, 0, 0, 0, 0, 0},{1, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 8}, 
	    {/*intp_sft*/0, 4},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H0V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/2, 0}, 
	    {/*intp_sft*/2, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{6, 2, 0, 0, 0, 0, 0, 0},{1, 3, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 16}, 
	    {/*intp_sft*/0, 5},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H2V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{4, 4, 0, 0, 0, 0, 0, 0},{1, 3, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 16}, 
	    {/*intp_sft*/0, 5},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{4, 4, 0, 0, 0, 0, 0, 0},{1, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 8}, 
	    {/*intp_sft*/0, 4},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
    },

    {
	/************* RV9_QPEL ***************/
	{/*H0V0*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, -5, 52, 20, -5, 1, 0, 0},{0},},
	    {/*intp_rnd*/32, 0}, 
	    {/*intp_sft*/6, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V0*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V0*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, -5, 20, 52, -5, 1, 0, 0},{0},},
	    {/*intp_rnd*/32, 0}, 
	    {/*intp_sft*/6, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V1*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, -5, 52, 20, -5, 1, 0, 0},{0},},
	    {/*intp_rnd*/32, 0}, 
	    {/*intp_sft*/6, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V1*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 52, 20, -5, 1, 0, 0}, {1, -5, 52, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/32, 32}, 
	    {/*intp_sft*/6, 6},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V1*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 52, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/16, 32}, 
	    {/*intp_sft*/5, 6},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V1*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 20, 52, -5, 1, 0, 0}, {1, -5, 52, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/32, 32}, 
	    {/*intp_sft*/6, 6},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V2*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
	    {/*intp_rnd*/16, 0}, 
	    {/*intp_sft*/5, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V2*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 52, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/32, 16}, 
	    {/*intp_sft*/6, 5},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V2*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/16, 16}, 
	    {/*intp_sft*/5, 5},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V2*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 20, 52, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
	    {/*intp_rnd*/32, 16}, 
	    {/*intp_sft*/6, 5},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V3*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, -5, 20, 52, -5, 1, 0, 0},{0},},
	    {/*intp_rnd*/32, 0}, 
	    {/*intp_sft*/6, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V3*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 52, 20, -5, 1, 0, 0}, {1, -5, 20, 52, -5, 1, 0, 0},},
	    {/*intp_rnd*/32, 32}, 
	    {/*intp_sft*/6, 6},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V3*/
	    TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 52, -5, 1, 0, 0},},
	    {/*intp_rnd*/16, 32}, 
	    {/*intp_sft*/5, 6},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 2}, 
	    {/*intp_sft*/0, 2},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
    },

    {
	/************* RV9_CPEL ***************/
	{/*H0V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/2, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/2, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V1*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/2, 0}, 
	    {/*intp_sft*/2, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V1*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0}, {3, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 7}, 
	    {/*intp_sft*/0, 4},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V1*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {3, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 4}, 
	    {/*intp_sft*/0, 3},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V1*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0}, {3, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 7}, 
	    {/*intp_sft*/0, 4},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 4}, 
	    {/*intp_sft*/0, 3},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 1}, 
	    {/*intp_sft*/0, 2},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 4}, 
	    {/*intp_sft*/0, 3},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/2, 0}, 
	    {/*intp_sft*/2, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0}, {1, 3, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 7}, 
	    {/*intp_sft*/0, 4},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 3, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 4}, 
	    {/*intp_sft*/0, 3},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V3*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 1}, 
	    {/*intp_sft*/0, 2},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
    },

    {
	/************* WMV2_QPEL ***************/
	{/*H0V0*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/8, 0}, 
	    {/*intp_sft*/4, 0},
	    {/*intp_sintp*/1, 0},
	    {/*intp_srnd*/1, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V0*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/8, 0}, 
	    {/*intp_sft*/4, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V0*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/8, 0}, 
	    {/*intp_sft*/4, 0},
	    {/*intp_sintp*/1, 0},
	    {/*intp_srnd*/1, 0},
	    {/*intp_sbias*/1, 0},
	},
	{/*H0V1*/0},
	{/*H1V1*/0},
	{/*H2V1*/0},
	{/*H3V1*/0},
	{/*H0V2*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/8, 0}, 
	    {/*intp_sft*/4, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V2*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0}, {-1, 9, 9, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/8, 8}, 
	    {/*intp_sft*/4, 4},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V2*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0}, {-1, 9, 9, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/8, 8}, 
	    {/*intp_sft*/4, 4},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V2*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0}, {-1, 9, 9, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/8, 8}, 
	    {/*intp_sft*/4, 4},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/0, 1},
	},
	{/*H0V3*/0},
	{/*H1V3*/0},
	{/*H2V3*/0},
	{/*H3V3*/0},
    },

    {
	/************* VC1_QPEL ***************/
	{/*H0V0*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-4, 53, 18, -3, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/32, 0}, 
	    {/*intp_sft*/6, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V0*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/8, 0}, 
	    {/*intp_sft*/4, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V0*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-3, 18, 53, -4, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/32, 0}, 
	    {/*intp_sft*/6, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V1*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-4, 53, 18, -3, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/31, 0}, 
	    {/*intp_sft*/6, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V1*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{-4, 53, 18, -3, 0, 0, 0, 0}, {-4, 53, 18, -3, 0, 0, 0, 0},},
	    {/*intp_rnd*/31, 32}, 
	    {/*intp_sft*/6, 6},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V1*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{-4, 53, 18, -3, 0, 0, 0, 0}, {-1, 9, 9, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/31, 8}, 
	    {/*intp_sft*/6, 4},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V1*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR},
	    {/*intp_coef*/{-4, 53, 18, -3, 0, 0, 0, 0}, {-3, 18, 53, -4, 0, 0, 0, 0},},
	    {/*intp_rnd*/31, 32},
	    {/*intp_sft*/6, 6},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V2*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/7, 0}, 
	    {/*intp_sft*/4, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V2*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0}, {-4, 53, 18, -3, 0, 0, 0, 0},},
	    {/*intp_rnd*/7, 32}, 
	    {/*intp_sft*/4, 6},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V2*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0}, {-1, 9, 9, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/7, 8}, 
	    {/*intp_sft*/4, 4},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V2*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0}, {-3, 18, 53, -4, 0, 0, 0, 0},},
	    {/*intp_rnd*/7, 32}, 
	    {/*intp_sft*/4, 6},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V3*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-3, 18, 53, -4, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/31, 0}, 
	    {/*intp_sft*/6, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V3*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{-3, 18, 53, -4, 0, 0, 0, 0}, {-4, 53, 18, -3, 0, 0, 0, 0},},
	    {/*intp_rnd*/31, 32}, 
	    {/*intp_sft*/6, 6},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V3*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{-3, 18, 53, -4, 0, 0, 0, 0}, {-1, 9, 9, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/31, 8}, 
	    {/*intp_sft*/6, 4},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V3*/
	    TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
	    {/*intp_coef*/{-3, 18, 53, -4, 0, 0, 0, 0}, {-3, 18, 53, -4, 0, 0, 0, 0},},
	    {/*intp_rnd*/31, 32}, 
	    {/*intp_sft*/6, 6},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
    },

    {
	/************* AVS_QPEL ***************/
	{/*H0V0*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-1, -2, 96, 42, -7, 0, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V0*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/4, 0}, 
	    {/*intp_sft*/3, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V0*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{0, -7, 42, 96, -2, -1, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V1*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-1, -2, 96, 42, -7, 0, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V1*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, IS_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0}, {-1, 5, -5, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 32}, 
	    {/*intp_sft*/0, 6},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V1*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{0, -1, 5, 5, -1, 0, 0, 0}, {-1, -2, 96, 42, -7, 0, 0, 0},},
	    {/*intp_rnd*/64, 0}, //{0,512} 
	    {/*intp_sft*/0, 10},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V1*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, IS_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0}, {-1, 5, -5, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 32}, 
	    {/*intp_sft*/0, 6},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/1, 0},
	},
	{/*H0V2*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/4, 0}, 
	    {/*intp_sft*/3, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V2*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, -2, 96, 42, -7, 0, 0, 0}, {0, -1, 5, 5, -1, 0, 0, 0},},
	    {/*intp_rnd*/64, 0}, //{0,512} 
	    {/*intp_sft*/0, 10},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V2*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0}, {-1, 5, 5, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 32}, 
	    {/*intp_sft*/0, 6},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V2*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{0, -7, 42, 96, -2, -1, 0, 0}, {0, -1, 5, 5, -1, 0, 0, 0},},
	    {/*intp_rnd*/64, 0}, //{0,512} 
	    {/*intp_sft*/0, 10},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V3*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{0, -7, 42, 96, -2, -1, 0, 0}, {0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V3*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, IS_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0}, {-1, 5, -5, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 32}, 
	    {/*intp_sft*/0, 6},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/0, 1},
	},
	{/*H2V3*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{0, -1, 5, 5, -1, 0, 0, 0}, {0, -7, 42, 96, -2, -1, 0, 0},},
	    {/*intp_rnd*/64, 0}, //{0,512} 
	    {/*intp_sft*/0, 10},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V3*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, IS_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0}, {-1, 5, -5, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/0, 32}, 
	    {/*intp_sft*/0, 6},
	    {/*intp_sintp*/0, 1},
	    {/*intp_srnd*/0, 1},
	    {/*intp_sbias*/1, 1},
	},
    },

    {
	/************* VP6_QPEL ***************/
	{/*H0V0*/
	    TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-4, 109, 24, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V0*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-4, 68, 68, -4, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V0*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{-1, 24, 109, -4, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V1*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-4, 109, 24, -1, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V1*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-4, 109, 24, -1, 0, 0, 0, 0}, {-4, 109, 24, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V1*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-4, 68, 68, -4, 0, 0, 0, 0}, {-4, 109, 24, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V1*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 24, 109, -4, 0, 0, 0, 0}, {-4, 109, 24, -1, 0, 0, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V2*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-4, 68, 68, -4, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V2*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-4, 109, 24, -1, 0, 0, 0, 0}, {-4, 68, 68, -4, 0, 0, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V2*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-4, 68, 68, -4, 0, 0, 0, 0}, {-4, 68, 68, -4, 0, 0, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V2*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 24, 109, -4, 0, 0, 0, 0}, {-4, 68, 68, -4, 0, 0, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V3*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{-1, 24, 109, -4, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V3*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-4, 109, 24, -1, 0, 0, 0, 0}, {-1, 24, 109, -4, 0, 0, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V3*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-4, 68, 68, -4, 0, 0, 0, 0}, {-1, 24, 109, -4, 0, 0, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V3*/
	    TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{-1, 24, 109, -4, 0, 0, 0, 0}, {-1, 24, 109, -4, 0, 0, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
    },

    {
	/************* VP8_QPEL ***************/
	{/*H0V0*/
	    TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{2, -11, 108, 36, -8, 1, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V0*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{3, -16, 77, 77, -16, 3, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V0*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, -8, 36, 108, -11, 2, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V1*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{2, -11, 108, 36, -8, 1, 0, 0}, {0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V1*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{2, -11, 108, 36, -8, 1, 0, 0}, {2, -11, 108, 36, -8, 1, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V1*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{3, -16, 77, 77, -16, 3, 0, 0}, {2, -11, 108, 36, -8, 1, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V1*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -8, 36, 108, -11, 2, 0, 0}, {2, -11, 108, 36, -8, 1, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V2*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{3, -16, 77, 77, -16, 3, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V2*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{2, -11, 108, 36, -8, 1, 0, 0}, {3, -16, 77, 77, -16, 3, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V2*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{3, -16, 77, 77, -16, 3, 0, 0}, {3, -16, 77, 77, -16, 3, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V2*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -8, 36, 108, -11, 2, 0, 0}, {3, -16, 77, 77, -16, 3, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H0V3*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, -8, 36, 108, -11, 2, 0, 0},{0},},
	    {/*intp_rnd*/64, 0}, 
	    {/*intp_sft*/7, 0},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H1V3*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{2, -11, 108, 36, -8, 1, 0, 0}, {1, -8, 36, 108, -11, 2, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H2V3*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{3, -16, 77, 77, -16, 3, 0, 0}, {1, -8, 36, 108, -11, 2, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
	{/*H3V3*/
	    TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, -8, 36, 108, -11, 2, 0, 0}, {1, -8, 36, 108, -11, 2, 0, 0},},
	    {/*intp_rnd*/64, 64}, 
	    {/*intp_sft*/7, 7},
	    {/*intp_sintp*/0, 0},
	    {/*intp_srnd*/0, 0},
	    {/*intp_sbias*/0, 0},
	},
    },

    {
	/************* VP8_EPEL ***************/
	{/*H0V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/0},
	{/*H2V0*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{0},{0},},
	    {/*intp_rnd*/4, 0}, 
	    {/*intp_sft*/3, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V0*/0},
	{/*H0V1*/0},
	{/*H1V1*/0},
	{/*H2V1*/0},
	{/*H3V1*/0},
	{/*H0V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{0},{0},},
	    {/*intp_rnd*/4, 0}, 
	    {/*intp_sft*/3, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V2*/0},
	{/*H2V2*/
	    TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{0},{0},},
	    {/*intp_rnd*/4, 4}, 
	    {/*intp_sft*/3, 3},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V2*/0},
	{/*H0V3*/0},
	{/*H1V3*/0},
	{/*H2V3*/0},
	{/*H3V3*/0},
    },

    {
	/************* VP8_BIL ***************/
	{/*H0V0*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/0, 0}, {0}, 
	    {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/0, 0}, 
	    {/*intp_sft*/0, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V0*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/2, 0}, 
	    {/*intp_sft*/2, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H2V0*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V0*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_HDIR, 0}, 
	    {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/2, 0}, 
	    {/*intp_sft*/2, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H0V1*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/2, 0}, 
	    {/*intp_sft*/2, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V1*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{3, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/2, 2}, 
	    {/*intp_sft*/2, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H2V1*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{3, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/1, 2}, 
	    {/*intp_sft*/1, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V1*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{3, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/2, 2}, 
	    {/*intp_sft*/2, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H0V2*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/1, 0}, 
	    {/*intp_sft*/1, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V2*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{1, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/2, 1}, 
	    {/*intp_sft*/2, 1},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H2V2*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{1, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/1, 1}, 
	    {/*intp_sft*/1, 1},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V2*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{1, 1, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/2, 1}, 
	    {/*intp_sft*/2, 1},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H0V3*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 0}, {INTP_VDIR, 0}, 
	    {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{0},},
	    {/*intp_rnd*/2, 0}, 
	    {/*intp_sft*/2, 0},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H1V3*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{1, 3, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/2, 2}, 
	    {/*intp_sft*/2, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H2V3*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{1, 3, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/1, 2}, 
	    {/*intp_sft*/1, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
	{/*H3V3*/
	    TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
	    {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
	    {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{1, 3, 0, 0, 0, 0, 0, 0},},
	    {/*intp_rnd*/2, 2}, 
	    {/*intp_sft*/2, 2},
	    {/*intp_sintp*/0},
	    {/*intp_srnd*/0},
	    {/*intp_sbias*/0},
	},
    },

    {
	/************* VP8_FPEL ***************/
	{/*H0V0*/0},
	{/*H1V0*/0},
	{/*H2V0*/0},
	{/*H3V0*/0},
	{/*H0V1*/0},
	{/*H1V1*/0},
	{/*H2V1*/0},
	{/*H3V1*/0},
	{/*H0V2*/0},
	{/*H1V2*/0},
	{/*H2V2*/0},
	{/*H3V2*/0},
	{/*H0V3*/0},
	{/*H1V3*/0},
	{/*H2V3*/0},
	{/*H3V3*/0},
    },
};

#endif /*__T_INTPID_H__*/
