#include "jzm_vpu.h"
/********************************************
  Motion interpolation programable table
*********************************************/
char AryFMT[] = {IS_SKIRT, IS_MIRROR, IS_SKIRT, IS_SKIRT,
			IS_SKIRT, IS_SKIRT, IS_SKIRT, IS_SKIRT, 
			IS_SKIRT, IS_SKIRT, IS_SKIRT, IS_SKIRT, 
			IS_SKIRT, IS_SKIRT, IS_SKIRT, IS_SKIRT};

char SubPel[] = {HPEL, QPEL, QPEL, EPEL, 
			QPEL, QPEL, QPEL, QPEL,
			QPEL, QPEL, QPEL, QPEL, 
			EPEL, HPEL, QPEL, QPEL};

IntpFMT_t IntpFMT[][16] = {
  {
    /************* MPEG_HPEL ***************/
    {/*H0V0*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/1, 0}, 
      {/*intp_sft*/1, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H2V0*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/1, 0}, 
      {/*intp_sft*/1, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H3V0*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/1, 0}, 
      {/*intp_sft*/1, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H0V1*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/1, 0}, 
      {/*intp_sft*/1, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V1*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
      {/*intp_rnd*/0, 2}, 
      {/*intp_sft*/0, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H2V1*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
      {/*intp_rnd*/0, 2}, 
      {/*intp_sft*/0, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H3V1*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
      {/*intp_rnd*/0, 2}, 
      {/*intp_sft*/0, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H0V2*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/1, 0}, 
      {/*intp_sft*/1, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V2*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
      {/*intp_rnd*/0, 2}, 
      {/*intp_sft*/0, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H2V2*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
      {/*intp_rnd*/0, 2}, 
      {/*intp_sft*/0, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H3V2*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
      {/*intp_rnd*/0, 2}, 
      {/*intp_sft*/0, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H0V3*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/1, 0}, 
      {/*intp_sft*/1, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V3*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
      {/*intp_rnd*/0, 2}, 
      {/*intp_sft*/0, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H2V3*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
      {/*intp_rnd*/0, 2}, 
      {/*intp_sft*/0, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H3V3*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0} },
      {/*intp_rnd*/0, 2}, 
      {/*intp_sft*/0, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
  },
  
  {
    /************* MPEG_QPEL ***************/
    {/*H0V0*/
      TAP8, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1},{0},},
      {/*intp_rnd*/15, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/1, 0},
      {/*intp_srnd*/1, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V0*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1},{0},},
      {/*intp_rnd*/15, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V0*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1},{0},},
      {/*intp_rnd*/15, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/1, 0},
      {/*intp_srnd*/1, 0},
      {/*intp_sbias*/1, 0},
    },
    {/*H0V1*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1},{0},},
      {/*intp_rnd*/15, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/1, 0},
      {/*intp_srnd*/1, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V1*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
      {/*intp_rnd*/15, 15}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/1, 1},
      {/*intp_srnd*/1, 1},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V1*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
      {/*intp_rnd*/15, 15}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V1*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
      {/*intp_rnd*/15, 15}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/1, 1},
      {/*intp_srnd*/1, 1},
      {/*intp_sbias*/1, 0},
    },
    {/*H0V2*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1},{0},},
      {/*intp_rnd*/15, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V2*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
      {/*intp_rnd*/15, 15}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/1, 0},
      {/*intp_srnd*/1, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V2*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
      {/*intp_rnd*/15, 15}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V2*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
      {/*intp_rnd*/15, 15}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/1, 0},
      {/*intp_srnd*/1, 0},
      {/*intp_sbias*/1, 0},
    },
    {/*H0V3*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1},{0},},
      {/*intp_rnd*/15, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/1, 0},
      {/*intp_srnd*/1, 0},
      {/*intp_sbias*/1, 0},
    },
    {/*H1V3*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
      {/*intp_rnd*/15, 15}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/1, 1},
      {/*intp_srnd*/1, 1},
      {/*intp_sbias*/0, 1},
    },
    {/*H2V3*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
      {/*intp_rnd*/15, 15}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/0, 1},
    },
    {/*H3V3*/
      TAP8, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 3, -6, 20, 20, -6, 3, -1}, {-1, 3, -6, 20, 20, -6, 3, -1},},
      {/*intp_rnd*/15, 15}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/1, 1},
      {/*intp_srnd*/1, 1},
      {/*intp_sbias*/1, 1},
    },
  },

  {
    /************* H264_QPEL ***************/
    {/*H0V0*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/1, 0},
      {/*intp_srnd*/1, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V0*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V0*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/1, 0},
      {/*intp_srnd*/1, 0},
      {/*intp_sbias*/1, 0},
    },
    {/*H0V1*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/1, 0},
      {/*intp_srnd*/1, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V1*/
      TAP6, {NOT_TCS, IS_SCS}, IS_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/16, 16}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V1*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 10},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V1*/
      TAP6, {NOT_TCS, IS_SCS}, IS_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/16, 16}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/1, 0},
    },
    {/*H0V2*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V2*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 10},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V2*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 10},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V2*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 10},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/0, 1},
    },
    {/*H0V3*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/1, 0},
      {/*intp_srnd*/1, 0},
      {/*intp_sbias*/1, 0},
    },
    {/*H1V3*/
      TAP6, {NOT_TCS, IS_SCS}, IS_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/16, 16}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/0, 1},
    },
    {/*H2V3*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 10},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/0, 1},
    },
    {/*H3V3*/
      TAP6, {NOT_TCS, IS_SCS}, IS_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/16, 16}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/1, 1},
    },
  },

  {
    /************* H264_EPEL ***************/
    {/*H0V0*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/0},
    {/*H2V0*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{0},{0},},
      {/*intp_rnd*/4, 0}, 
      {/*intp_sft*/3, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H3V0*/0},
    {/*H0V1*/0},
    {/*H1V1*/0},
    {/*H2V1*/0},
    {/*H3V1*/0},
    {/*H0V2*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{0},{0},},
      {/*intp_rnd*/4, 0}, 
      {/*intp_sft*/3, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V2*/0},
    {/*H2V2*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{0},{0},},
      {/*intp_rnd*/0, 32}, 
      {/*intp_sft*/0, 6},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H3V2*/0},
    {/*H0V3*/0},
    {/*H1V3*/0},
    {/*H2V3*/0},
    {/*H3V3*/0},
  },

  {
    /************* RV8_TPEL ***************/
    {/*H0V0*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-1, 12, 6, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/8, 0}, 
      {/*intp_sft*/4, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V0*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-1, 6, 12, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/8, 0}, 
      {/*intp_sft*/4, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V0*/0},
    {/*H0V1*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-1, 12, 6, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/8, 0}, 
      {/*intp_sft*/4, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V1*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 12, 6, -1, 0, 0, 0, 0}, {-1, 12, 6, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/8, 0}, //{0,128}
      {/*intp_sft*/0, 8},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V1*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 6, 12, -1, 0, 0, 0, 0}, {-1, 12, 6, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/8, 0}, //{0,128}
      {/*intp_sft*/0, 8},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V1*/0},
    {/*H0V2*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-1, 6, 12, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/8, 0}, 
      {/*intp_sft*/4, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V2*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 12, 6, -1, 0, 0, 0, 0}, {-1, 6, 12, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/8, 0}, //{0,128}
      {/*intp_sft*/0, 8},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V2*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 6, 12, -1, 0, 0, 0, 0}, {-1, 6, 12, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/8, 0}, //{0,128}
      {/*intp_sft*/0, 8},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V2*/0},
    {/*H0V3*/0},
    {/*H1V3*/0},
    {/*H2V3*/0},
    {/*H3V3*/0},
  },

  {
    /************* RV9_QPEL ***************/
    {/*H0V0*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{1, -5, 52, 20, -5, 1, 0, 0},{0},},
      {/*intp_rnd*/32, 0}, 
      {/*intp_sft*/6, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V0*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V0*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{1, -5, 20, 52, -5, 1, 0, 0},{0},},
      {/*intp_rnd*/32, 0}, 
      {/*intp_sft*/6, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V1*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{1, -5, 52, 20, -5, 1, 0, 0},{0},},
      {/*intp_rnd*/32, 0}, 
      {/*intp_sft*/6, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V1*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 52, 20, -5, 1, 0, 0}, {1, -5, 52, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/32, 32}, 
      {/*intp_sft*/6, 6},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V1*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 52, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/16, 32}, 
      {/*intp_sft*/5, 6},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V1*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 20, 52, -5, 1, 0, 0}, {1, -5, 52, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/32, 32}, 
      {/*intp_sft*/6, 6},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V2*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0},{0},},
      {/*intp_rnd*/16, 0}, 
      {/*intp_sft*/5, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V2*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 52, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/32, 16}, 
      {/*intp_sft*/6, 5},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V2*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/16, 16}, 
      {/*intp_sft*/5, 5},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V2*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 20, 52, -5, 1, 0, 0}, {1, -5, 20, 20, -5, 1, 0, 0},},
      {/*intp_rnd*/32, 16}, 
      {/*intp_sft*/6, 5},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V3*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{1, -5, 20, 52, -5, 1, 0, 0},{0},},
      {/*intp_rnd*/32, 0}, 
      {/*intp_sft*/6, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V3*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 52, 20, -5, 1, 0, 0}, {1, -5, 20, 52, -5, 1, 0, 0},},
      {/*intp_rnd*/32, 32}, 
      {/*intp_sft*/6, 6},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V3*/
      TAP6, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -5, 20, 20, -5, 1, 0, 0}, {1, -5, 20, 52, -5, 1, 0, 0},},
      {/*intp_rnd*/16, 32}, 
      {/*intp_sft*/5, 6},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V3*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 2}, 
      {/*intp_sft*/0, 2},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
  },

  {
    /************* RV9_CPEL ***************/
    {/*H0V0*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/1, 0}, 
      {/*intp_sft*/2, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V0*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/1, 0}, 
      {/*intp_sft*/1, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V0*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/1, 0}, 
      {/*intp_sft*/2, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V1*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/2, 0}, 
      {/*intp_sft*/2, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V1*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0}, {3, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 7}, 
      {/*intp_sft*/0, 4},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V1*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {3, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 4}, 
      {/*intp_sft*/0, 3},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V1*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0}, {3, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 7}, 
      {/*intp_sft*/0, 4},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V2*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/1, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V2*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 4}, 
      {/*intp_sft*/0, 3},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V2*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 1}, 
      {/*intp_sft*/0, 2},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V2*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 4}, 
      {/*intp_sft*/0, 3},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V3*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/2, 0}, 
      {/*intp_sft*/2, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V3*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0}, {1, 3, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 7}, 
      {/*intp_sft*/0, 4},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V3*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 3, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 4}, 
      {/*intp_sft*/0, 3},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V3*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 1}, 
      {/*intp_sft*/0, 2},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
  },

  {
    /************* WMV2_QPEL ***************/
    {/*H0V0*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/8, 0}, 
      {/*intp_sft*/4, 0},
      {/*intp_sintp*/1, 0},
      {/*intp_srnd*/1, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V0*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/8, 0}, 
      {/*intp_sft*/4, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V0*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/8, 0}, 
      {/*intp_sft*/4, 0},
      {/*intp_sintp*/1, 0},
      {/*intp_srnd*/1, 0},
      {/*intp_sbias*/1, 0},
    },
    {/*H0V1*/0},
    {/*H1V1*/0},
    {/*H2V1*/0},
    {/*H3V1*/0},
    {/*H0V2*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/8, 0}, 
      {/*intp_sft*/4, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V2*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0}, {-1, 9, 9, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/8, 8}, 
      {/*intp_sft*/4, 4},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V2*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0}, {-1, 9, 9, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/8, 8}, 
      {/*intp_sft*/4, 4},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V2*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0}, {-1, 9, 9, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/8, 8}, 
      {/*intp_sft*/4, 4},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/0, 1},
    },
    {/*H0V3*/0},
    {/*H1V3*/0},
    {/*H2V3*/0},
    {/*H3V3*/0},
  },

  {
    /************* VC1_QPEL ***************/
    {/*H0V0*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-4, 53, 18, -3, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/32, 0}, 
      {/*intp_sft*/6, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V0*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/8, 0}, 
      {/*intp_sft*/4, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V0*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-3, 18, 53, -4, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/32, 0}, 
      {/*intp_sft*/6, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V1*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-4, 53, 18, -3, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/31, 0}, 
      {/*intp_sft*/6, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V1*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{-4, 53, 18, -3, 0, 0, 0, 0}, {-4, 53, 18, -3, 0, 0, 0, 0},},
      {/*intp_rnd*/31, 32}, 
      {/*intp_sft*/6, 6},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V1*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{-4, 53, 18, -3, 0, 0, 0, 0}, {-1, 9, 9, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/31, 8}, 
      {/*intp_sft*/6, 4},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V1*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR},
      {/*intp_coef*/{-4, 53, 18, -3, 0, 0, 0, 0}, {-3, 18, 53, -4, 0, 0, 0, 0},},
      {/*intp_rnd*/31, 32},
      {/*intp_sft*/6, 6},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V2*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/7, 0}, 
      {/*intp_sft*/4, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V2*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0}, {-4, 53, 18, -3, 0, 0, 0, 0},},
      {/*intp_rnd*/7, 32}, 
      {/*intp_sft*/4, 6},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V2*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0}, {-1, 9, 9, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/7, 8}, 
      {/*intp_sft*/4, 4},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V2*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{-1, 9, 9, -1, 0, 0, 0, 0}, {-3, 18, 53, -4, 0, 0, 0, 0},},
      {/*intp_rnd*/7, 32}, 
      {/*intp_sft*/4, 6},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V3*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-3, 18, 53, -4, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/31, 0}, 
      {/*intp_sft*/6, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V3*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{-3, 18, 53, -4, 0, 0, 0, 0}, {-4, 53, 18, -3, 0, 0, 0, 0},},
      {/*intp_rnd*/31, 32}, 
      {/*intp_sft*/6, 6},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V3*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{-3, 18, 53, -4, 0, 0, 0, 0}, {-1, 9, 9, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/31, 8}, 
      {/*intp_sft*/6, 4},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V3*/
      TAP4, {NOT_TCS, IS_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_VDIR, INTP_HDIR}, 
      {/*intp_coef*/{-3, 18, 53, -4, 0, 0, 0, 0}, {-3, 18, 53, -4, 0, 0, 0, 0},},
      {/*intp_rnd*/31, 32}, 
      {/*intp_sft*/6, 6},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
  },

  {
    /************* AVS_QPEL ***************/
    {/*H0V0*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-1, -2, 96, 42, -7, 0, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V0*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/4, 0}, 
      {/*intp_sft*/3, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V0*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{0, -7, 42, 96, -2, -1, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V1*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-1, -2, 96, 42, -7, 0, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V1*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, IS_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0}, {-1, 5, -5, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 32}, 
      {/*intp_sft*/0, 6},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V1*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{0, -1, 5, 5, -1, 0, 0, 0}, {-1, -2, 96, 42, -7, 0, 0, 0},},
      {/*intp_rnd*/64, 0}, //{0,512} 
      {/*intp_sft*/0, 10},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V1*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, IS_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0}, {-1, 5, -5, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 32}, 
      {/*intp_sft*/0, 6},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/1, 0},
    },
    {/*H0V2*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/4, 0}, 
      {/*intp_sft*/3, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V2*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, -2, 96, 42, -7, 0, 0, 0}, {0, -1, 5, 5, -1, 0, 0, 0},},
      {/*intp_rnd*/64, 0}, //{0,512} 
      {/*intp_sft*/0, 10},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V2*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0}, {-1, 5, 5, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 32}, 
      {/*intp_sft*/0, 6},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V2*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{0, -7, 42, 96, -2, -1, 0, 0}, {0, -1, 5, 5, -1, 0, 0, 0},},
      {/*intp_rnd*/64, 0}, //{0,512} 
      {/*intp_sft*/0, 10},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V3*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{0, -7, 42, 96, -2, -1, 0, 0}, {0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V3*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, IS_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0}, {-1, 5, -5, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 32}, 
      {/*intp_sft*/0, 6},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/0, 1},
    },
    {/*H2V3*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{0, -1, 5, 5, -1, 0, 0, 0}, {0, -7, 42, 96, -2, -1, 0, 0},},
      {/*intp_rnd*/64, 0}, //{0,512} 
      {/*intp_sft*/0, 10},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V3*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, IS_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 5, 5, -1, 0, 0, 0, 0}, {-1, 5, -5, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/0, 32}, 
      {/*intp_sft*/0, 6},
      {/*intp_sintp*/0, 1},
      {/*intp_srnd*/0, 1},
      {/*intp_sbias*/1, 1},
    },
  },

  {
    /************* VP6_QPEL ***************/
    {/*H0V0*/
      TAP4, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-4, 109, 24, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V0*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-4, 68, 68, -4, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V0*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{-1, 24, 109, -4, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V1*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-4, 109, 24, -1, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V1*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-4, 109, 24, -1, 0, 0, 0, 0}, {-4, 109, 24, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V1*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-4, 68, 68, -4, 0, 0, 0, 0}, {-4, 109, 24, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V1*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 24, 109, -4, 0, 0, 0, 0}, {-4, 109, 24, -1, 0, 0, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V2*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-4, 68, 68, -4, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V2*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-4, 109, 24, -1, 0, 0, 0, 0}, {-4, 68, 68, -4, 0, 0, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V2*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-4, 68, 68, -4, 0, 0, 0, 0}, {-4, 68, 68, -4, 0, 0, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V2*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 24, 109, -4, 0, 0, 0, 0}, {-4, 68, 68, -4, 0, 0, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V3*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{-1, 24, 109, -4, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V3*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-4, 109, 24, -1, 0, 0, 0, 0}, {-1, 24, 109, -4, 0, 0, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V3*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-4, 68, 68, -4, 0, 0, 0, 0}, {-1, 24, 109, -4, 0, 0, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V3*/
      TAP4, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{-1, 24, 109, -4, 0, 0, 0, 0}, {-1, 24, 109, -4, 0, 0, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
  },

  {
    /************* VP8_QPEL ***************/
    {/*H0V0*/
      TAP6, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{2, -11, 108, 36, -8, 1, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V0*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{3, -16, 77, 77, -16, 3, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V0*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{1, -8, 36, 108, -11, 2, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V1*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{2, -11, 108, 36, -8, 1, 0, 0}, {0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V1*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{2, -11, 108, 36, -8, 1, 0, 0}, {2, -11, 108, 36, -8, 1, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V1*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{3, -16, 77, 77, -16, 3, 0, 0}, {2, -11, 108, 36, -8, 1, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V1*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -8, 36, 108, -11, 2, 0, 0}, {2, -11, 108, 36, -8, 1, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V2*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{3, -16, 77, 77, -16, 3, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V2*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{2, -11, 108, 36, -8, 1, 0, 0}, {3, -16, 77, 77, -16, 3, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V2*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{3, -16, 77, 77, -16, 3, 0, 0}, {3, -16, 77, 77, -16, 3, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V2*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -8, 36, 108, -11, 2, 0, 0}, {3, -16, 77, 77, -16, 3, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H0V3*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{1, -8, 36, 108, -11, 2, 0, 0},{0},},
      {/*intp_rnd*/64, 0}, 
      {/*intp_sft*/7, 0},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H1V3*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{2, -11, 108, 36, -8, 1, 0, 0}, {1, -8, 36, 108, -11, 2, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H2V3*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{3, -16, 77, 77, -16, 3, 0, 0}, {1, -8, 36, 108, -11, 2, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
    {/*H3V3*/
      TAP6, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, -8, 36, 108, -11, 2, 0, 0}, {1, -8, 36, 108, -11, 2, 0, 0},},
      {/*intp_rnd*/64, 64}, 
      {/*intp_sft*/7, 7},
      {/*intp_sintp*/0, 0},
      {/*intp_srnd*/0, 0},
      {/*intp_sbias*/0, 0},
    },
  },

  {
    /************* VP8_EPEL ***************/
    {/*H0V0*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/0},
    {/*H2V0*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{0},{0},},
      {/*intp_rnd*/4, 0}, 
      {/*intp_sft*/3, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H3V0*/0},
    {/*H0V1*/0},
    {/*H1V1*/0},
    {/*H2V1*/0},
    {/*H3V1*/0},
    {/*H0V2*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{0},{0},},
      {/*intp_rnd*/4, 0}, 
      {/*intp_sft*/3, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V2*/0},
    {/*H2V2*/
      TAP2, {NOT_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{0},{0},},
      {/*intp_rnd*/4, 4}, 
      {/*intp_sft*/3, 3},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H3V2*/0},
    {/*H0V3*/0},
    {/*H1V3*/0},
    {/*H2V3*/0},
    {/*H3V3*/0},
  },

  {
    /************* VP8_BIL ***************/
    {/*H0V0*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/0, 0}, {0}, 
      {/*intp_coef*/{1, 0, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/0, 0}, 
      {/*intp_sft*/0, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V0*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/2, 0}, 
      {/*intp_sft*/2, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H2V0*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/1, 0}, 
      {/*intp_sft*/1, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H3V0*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_HDIR, 0}, 
      {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/2, 0}, 
      {/*intp_sft*/2, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H0V1*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/2, 0}, 
      {/*intp_sft*/2, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V1*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{3, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/2, 2}, 
      {/*intp_sft*/2, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H2V1*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{3, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/1, 2}, 
      {/*intp_sft*/1, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H3V1*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{3, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/2, 2}, 
      {/*intp_sft*/2, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H0V2*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/1, 0}, 
      {/*intp_sft*/1, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V2*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{1, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/2, 1}, 
      {/*intp_sft*/2, 1},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H2V2*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{1, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/1, 1}, 
      {/*intp_sft*/1, 1},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H3V2*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{1, 1, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/2, 1}, 
      {/*intp_sft*/2, 1},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H0V3*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 0}, {INTP_VDIR, 0}, 
      {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{0},},
      {/*intp_rnd*/2, 0}, 
      {/*intp_sft*/2, 0},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H1V3*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{3, 1, 0, 0, 0, 0, 0, 0},{1, 3, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/2, 2}, 
      {/*intp_sft*/2, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H2V3*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 1, 0, 0, 0, 0, 0, 0},{1, 3, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/1, 2}, 
      {/*intp_sft*/1, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
    {/*H3V3*/
      TAP2, {IS_TCS, NOT_SCS}, NOT_HLDGL, NOT_AVSDGL,
      {/*intp*/1, 1}, {INTP_HDIR, INTP_VDIR}, 
      {/*intp_coef*/{1, 3, 0, 0, 0, 0, 0, 0},{1, 3, 0, 0, 0, 0, 0, 0},},
      {/*intp_rnd*/2, 2}, 
      {/*intp_sft*/2, 2},
      {/*intp_sintp*/0},
      {/*intp_srnd*/0},
      {/*intp_sbias*/0},
    },
  },

  {
    /************* VP8_FPEL ***************/
    {/*H0V0*/0},
    {/*H1V0*/0},
    {/*H2V0*/0},
    {/*H3V0*/0},
    {/*H0V1*/0},
    {/*H1V1*/0},
    {/*H2V1*/0},
    {/*H3V1*/0},
    {/*H0V2*/0},
    {/*H1V2*/0},
    {/*H2V2*/0},
    {/*H3V2*/0},
    {/*H0V3*/0},
    {/*H1V3*/0},
    {/*H2V3*/0},
    {/*H3V3*/0},
  },
};
