/* ***** BEGIN LICENSE BLOCK *****   
 * Source last modified: $Id: cpl_table_4.c,v 1.1.1.1 2007/12/07 08:11:45 zpxu Exp $ 
 * 
 * REALNETWORKS CONFIDENTIAL--NOT FOR DISTRIBUTION IN SOURCE CODE FORM   
 * Portions Copyright (c) 1995-2005 RealNetworks, Inc.   
 * All Rights Reserved.   
 *   
 * The contents of this file, and the files included with this file, 
 * are subject to the current version of the RealNetworks Community 
 * Source License (the "RCSL"), including Attachment G and any 
 * applicable attachments, all available at 
 * http://www.helixcommunity.org/content/rcsl.  You may also obtain 
 * the license terms directly from RealNetworks.  You may not use this 
 * file except in compliance with the RCSL and its Attachments. There 
 * are no redistribution rights for the source code of this 
 * file. Please see the applicable RCSL for the rights, obligations 
 * and limitations governing use of the contents of the file. 
 *   
 * This file is part of the Helix DNA Technology. RealNetworks is the 
 * developer of the Original Code and owns the copyrights in the 
 * portions it created. 
 *   
 * This file, and the files included with this file, is distributed 
 * and made available on an 'AS IS' basis, WITHOUT WARRANTY OF ANY 
 * KIND, EITHER EXPRESS OR IMPLIED, AND REALNETWORKS HEREBY DISCLAIMS 
 * ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET 
 * ENJOYMENT OR NON-INFRINGEMENT. 
 *   
 * Technology Compatibility Kit Test Suite(s) Location:   
 * https://rarvcode-tck.helixcommunity.org   
 *   
 * Contributor(s):   
 *   
 * ***** END LICENSE BLOCK ***** */   

/*-------------------------------------------------------------------------*
 *	FileName : cpl_table_4.c												   *
 *																		   *
 *	Huffman lookup table(s) generated by utility for huffman tree(s) 	   *
 *		cpl_table_4 of real audio decoder.									   *
 *																		   *
 *																		   *
 *  NOTE : CPL_TABLE_4_BIT_COUNT no. of bits should be read in the			   *
 *			DecodeNextSymbolFromTree() function for the table			   *
 *																		   *
 *-------------------------------------------------------------------------*/


#ifdef _HUFFMAN_TABLES_

#include "cpl_table_4.h"

#pragma DATA_ALIGN( RA_TNI_cpl_table_4, 2 )	 // align on 32-bit boundary

const HuffmanTableNode RA_TNI_cpl_table_4[] = { 
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  7 , 1  },
	{  6 , 3  },
	{  6 , 3  },
	{  6 , 3  },
	{  6 , 3  },
	{  6 , 3  },
	{  6 , 3  },
	{  6 , 3  },
	{  6 , 3  },
	{  8 , 3  },
	{  8 , 3  },
	{  8 , 3  },
	{  8 , 3  },
	{  8 , 3  },
	{  8 , 3  },
	{  8 , 3  },
	{  8 , 3  },
	{  5 , 4  },
	{  5 , 4  },
	{  5 , 4  },
	{  5 , 4  },
	{  9 , 4  },
	{  9 , 4  },
	{  9 , 4  },
	{  9 , 4  },
	{  4 , 5  },
	{  4 , 5  },
	{  10 , 5  },
	{  10 , 5  },
	{  3 , 6  },
	{  11 , 6  },
	{  64 , -6 },
	{  72 , -6 },

	{  2 , 1  },
	{  2 , 1  },
	{  2 , 1  },
	{  2 , 1  },
	{  12 , 1  },
	{  12 , 1  },
	{  12 , 1  },
	{  12 , 1  },

	{  0 , 2  },
	{  0 , 2  },
	{  1 , 2  },
	{  1 , 2  },
	{  13 , 2  },
	{  13 , 2  },
	{  14 , 2  },
	{  14 , 2  }

};

#endif // _HUFFMAN_TABLES_
