/* ***** BEGIN LICENSE BLOCK *****   
 * Source last modified: $Id: cpl_table_5.c,v 1.1.1.1 2007/12/07 08:11:45 zpxu Exp $ 
 * 
 * REALNETWORKS CONFIDENTIAL--NOT FOR DISTRIBUTION IN SOURCE CODE FORM   
 * Portions Copyright (c) 1995-2005 RealNetworks, Inc.   
 * All Rights Reserved.   
 *   
 * The contents of this file, and the files included with this file, 
 * are subject to the current version of the RealNetworks Community 
 * Source License (the "RCSL"), including Attachment G and any 
 * applicable attachments, all available at 
 * http://www.helixcommunity.org/content/rcsl.  You may also obtain 
 * the license terms directly from RealNetworks.  You may not use this 
 * file except in compliance with the RCSL and its Attachments. There 
 * are no redistribution rights for the source code of this 
 * file. Please see the applicable RCSL for the rights, obligations 
 * and limitations governing use of the contents of the file. 
 *   
 * This file is part of the Helix DNA Technology. RealNetworks is the 
 * developer of the Original Code and owns the copyrights in the 
 * portions it created. 
 *   
 * This file, and the files included with this file, is distributed 
 * and made available on an 'AS IS' basis, WITHOUT WARRANTY OF ANY 
 * KIND, EITHER EXPRESS OR IMPLIED, AND REALNETWORKS HEREBY DISCLAIMS 
 * ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET 
 * ENJOYMENT OR NON-INFRINGEMENT. 
 *   
 * Technology Compatibility Kit Test Suite(s) Location:   
 * https://rarvcode-tck.helixcommunity.org   
 *   
 * Contributor(s):   
 *   
 * ***** END LICENSE BLOCK ***** */   

/*-------------------------------------------------------------------------*
 *	FileName : cpl_table_5.c												   *
 *																		   *
 *	Huffman lookup table(s) generated by utility for huffman tree(s) 	   *
 *		cpl_table_5 of real audio decoder.									   *
 *																		   *
 *																		   *
 *  NOTE : CPL_TABLE_5_BIT_COUNT no. of bits should be read in the			   *
 *			DecodeNextSymbolFromTree() function for the table			   *
 *																		   *
 *-------------------------------------------------------------------------*/


#ifdef _HUFFMAN_TABLES_

#include "cpl_table_5.h"

#pragma DATA_ALIGN( RA_TNI_cpl_table_5, 2 )	 // align on 32-bit boundary

const HuffmanTableNode RA_TNI_cpl_table_5[] = { 
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  15 , 1  },
	{  14 , 3  },
	{  14 , 3  },
	{  14 , 3  },
	{  14 , 3  },
	{  14 , 3  },
	{  14 , 3  },
	{  14 , 3  },
	{  14 , 3  },
	{  16 , 3  },
	{  16 , 3  },
	{  16 , 3  },
	{  16 , 3  },
	{  16 , 3  },
	{  16 , 3  },
	{  16 , 3  },
	{  16 , 3  },
	{  12 , 5  },
	{  12 , 5  },
	{  13 , 5  },
	{  13 , 5  },
	{  17 , 5  },
	{  17 , 5  },
	{  18 , 5  },
	{  18 , 5  },
	{  10 , 6  },
	{  11 , 6  },
	{  19 , 6  },
	{  20 , 6  },
	{  64 , -6 },
	{  72 , -6 },
	{  80 , -6 },
	{  88 , -6 },

	{  8 , 1  },
	{  8 , 1  },
	{  8 , 1  },
	{  8 , 1  },
	{  9 , 1  },
	{  9 , 1  },
	{  9 , 1  },
	{  9 , 1  },

	{  21 , 1  },
	{  21 , 1  },
	{  21 , 1  },
	{  21 , 1  },
	{  22 , 1  },
	{  22 , 1  },
	{  22 , 1  },
	{  22 , 1  },

	{  6 , 2  },
	{  6 , 2  },
	{  7 , 2  },
	{  7 , 2  },
	{  23 , 2  },
	{  23 , 2  },
	{  24 , 2  },
	{  24 , 2  },

	{  4 , 3  },
	{  5 , 3  },
	{  25 , 3  },
	{  26 , 3  },
	{  8 , -3 },
	{  16 , -3 },
	{  24 , -3 },
	{  32 , -3 },

	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  1 , 1  },
	{  1 , 1  },
	{  1 , 1  },
	{  1 , 1  },

	{  2 , 1  },
	{  2 , 1  },
	{  2 , 1  },
	{  2 , 1  },
	{  3 , 1  },
	{  3 , 1  },
	{  3 , 1  },
	{  3 , 1  },

	{  27 , 1  },
	{  27 , 1  },
	{  27 , 1  },
	{  27 , 1  },
	{  28 , 1  },
	{  28 , 1  },
	{  28 , 1  },
	{  28 , 1  },

	{  29 , 1  },
	{  29 , 1  },
	{  29 , 1  },
	{  29 , 1  },
	{  30 , 1  },
	{  30 , 1  },
	{  30 , 1  },
	{  30 , 1  }

};

#endif // _HUFFMAN_TABLES_
