/* ***** BEGIN LICENSE BLOCK *****   
 * Source last modified: $Id: sqvh_table_2.c,v 1.1.1.1 2007/12/07 08:11:46 zpxu Exp $ 
 * 
 * REALNETWORKS CONFIDENTIAL--NOT FOR DISTRIBUTION IN SOURCE CODE FORM   
 * Portions Copyright (c) 1995-2005 RealNetworks, Inc.   
 * All Rights Reserved.   
 *   
 * The contents of this file, and the files included with this file, 
 * are subject to the current version of the RealNetworks Community 
 * Source License (the "RCSL"), including Attachment G and any 
 * applicable attachments, all available at 
 * http://www.helixcommunity.org/content/rcsl.  You may also obtain 
 * the license terms directly from RealNetworks.  You may not use this 
 * file except in compliance with the RCSL and its Attachments. There 
 * are no redistribution rights for the source code of this 
 * file. Please see the applicable RCSL for the rights, obligations 
 * and limitations governing use of the contents of the file. 
 *   
 * This file is part of the Helix DNA Technology. RealNetworks is the 
 * developer of the Original Code and owns the copyrights in the 
 * portions it created. 
 *   
 * This file, and the files included with this file, is distributed 
 * and made available on an 'AS IS' basis, WITHOUT WARRANTY OF ANY 
 * KIND, EITHER EXPRESS OR IMPLIED, AND REALNETWORKS HEREBY DISCLAIMS 
 * ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET 
 * ENJOYMENT OR NON-INFRINGEMENT. 
 *   
 * Technology Compatibility Kit Test Suite(s) Location:   
 * https://rarvcode-tck.helixcommunity.org   
 *   
 * Contributor(s):   
 *   
 * ***** END LICENSE BLOCK ***** */   

/*-------------------------------------------------------------------------*
 *	FileName : sqvh_table_2.c												   *
 *																		   *
 *	Huffman lookup table(s) generated by utility for huffman tree(s) 	   *
 *		sqvh_table_2 of real audio decoder.									   *
 *																		   *
 *																		   *
 *  NOTE : SQVH_TABLE_2_BIT_COUNT no. of bits should be read in the			   *
 *			DecodeNextSymbolFromTree() function for the table			   *
 *																		   *
 *-------------------------------------------------------------------------*/


#ifdef _HUFFMAN_TABLES_

#include "sqvh_table_2.h"

#pragma DATA_ALIGN( RA_TNI_sqvh_table_2, 2 )	 // align on 32-bit boundary
 
#ifdef CONST_TABLE_DMA
#pragma DATA_SECTION( RA_TNI_sqvh_table_2, "CONST_TABLE_DMA_SECTION") 
#endif 
 
const HuffmanTableNode RA_TNI_sqvh_table_2[] = { 
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  0 , 1  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  7 , 3  },
	{  1 , 4  },
	{  1 , 4  },
	{  1 , 4  },
	{  1 , 4  },
	{  1 , 4  },
	{  1 , 4  },
	{  1 , 4  },
	{  1 , 4  },
	{  8 , 4  },
	{  8 , 4  },
	{  8 , 4  },
	{  8 , 4  },
	{  8 , 4  },
	{  8 , 4  },
	{  8 , 4  },
	{  8 , 4  },
	{  2 , 5  },
	{  2 , 5  },
	{  2 , 5  },
	{  2 , 5  },
	{  9 , 5  },
	{  9 , 5  },
	{  9 , 5  },
	{  9 , 5  },
	{  14 , 5  },
	{  14 , 5  },
	{  14 , 5  },
	{  14 , 5  },
	{  15 , 5  },
	{  15 , 5  },
	{  15 , 5  },
	{  15 , 5  },
	{  16 , 6  },
	{  16 , 6  },
	{  22 , 6  },
	{  22 , 6  },
	{  3 , 7  },
	{  10 , 7  },
	{  17 , 7  },
	{  21 , 7  },
	{  23 , 7  },
	{  128 , -7 },
	{  136 , -7 },
	{  144 , -7 },
	{  152 , -7 },
	{  160 , -7 },
	{  168 , -7 },
	{  176 , -7 },

	{  4 , 1  },
	{  4 , 1  },
	{  4 , 1  },
	{  4 , 1  },
	{  11 , 1  },
	{  11 , 1  },
	{  11 , 1  },
	{  11 , 1  },

	{  18 , 1  },
	{  18 , 1  },
	{  18 , 1  },
	{  18 , 1  },
	{  24 , 1  },
	{  24 , 1  },
	{  24 , 1  },
	{  24 , 1  },

	{  28 , 1  },
	{  28 , 1  },
	{  28 , 1  },
	{  28 , 1  },
	{  29 , 1  },
	{  29 , 1  },
	{  29 , 1  },
	{  29 , 1  },

	{  30 , 1  },
	{  30 , 1  },
	{  30 , 1  },
	{  30 , 1  },
	{  35 , 1  },
	{  35 , 1  },
	{  35 , 1  },
	{  35 , 1  },

	{  5 , 2  },
	{  5 , 2  },
	{  12 , 2  },
	{  12 , 2  },
	{  25 , 2  },
	{  25 , 2  },
	{  31 , 2  },
	{  31 , 2  },

	{  36 , 2  },
	{  36 , 2  },
	{  37 , 2  },
	{  37 , 2  },
	{  42 , 2  },
	{  42 , 2  },
	{  6 , 3  },
	{  13 , 3  },

	{  19 , 3  },
	{  20 , 3  },
	{  26 , 3  },
	{  32 , 3  },
	{  38 , 3  },
	{  43 , 3  },
	{  8 , -3 },
	{  16 , -3 },

	{  39 , 1  },
	{  39 , 1  },
	{  39 , 1  },
	{  39 , 1  },
	{  44 , 1  },
	{  44 , 1  },
	{  44 , 1  },
	{  44 , 1  },

	{  27 , 2  },
	{  27 , 2  },
	{  33 , 2  },
	{  33 , 2  },
	{  45 , 2  },
	{  45 , 2  },
	{  46 , 3  },
	{  8 , -3 },

	{  34 , 1  },
	{  34 , 1  },
	{  34 , 1  },
	{  34 , 1  },
	{  40 , 2  },
	{  40 , 2  },
	{  41 , 3  },
	{  47 , 3  }

};

#endif // _HUFFMAN_TABLES_
